# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      # Check for npm updates at 1am UTC
      time: "01:00"
    pull-request-branch-name:
      # Separate sections of the branch name with a hyphen
      # for example, `dependabot-npm_and_yarn-next_js-acorn-6.4.1`
      separator: "-"
    # Specify labels for npm pull requests
    labels:
      - "npm"
      - "dependencies"
    commit-message:
      # Prefix all commit messages with "npm"
      prefix: "npm"
    # Add assignees
    assignees:
      - "guilhermeborgesbastos"
